### ISSUE TITLE
Can't build with aeson-2.0

### ISSUE THREAD

**Issue by ocharles** [cachix/elm2nix#46]
```
Building library for elm2nix-0.2.1..
[1 of 4] Compiling Elm2Nix.FixedOutput ( src/Elm2Nix/FixedOutput.hs, dist/build/Elm2Nix/FixedOutput.o, dist/build/Elm2Nix/FixedOutput.dyn_o )
[2 of 4] Compiling Elm2Nix.PackagesSnapshot ( src/Elm2Nix/PackagesSnapshot.hs, dist/build/Elm2Nix/PackagesSnapshot.o, dist/build/Elm2Nix/PackagesSnapshot.dyn_o )
[3 of 4] Compiling Elm2Nix          ( src/Elm2Nix.hs, dist/build/Elm2Nix.o, dist/build/Elm2Nix.dyn_o )

src/Elm2Nix.hs:53:25: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HashMap Text Value’
      Expected type: HashMap Text Value
        Actual type: Json.Object
    • In the first argument of ‘tryLookup’, namely ‘hm’
      In a stmt of a 'do' block: deps <- tryLookup hm depsKey
      In the expression:
        do deps <- tryLookup hm depsKey
           case deps of
             Object dhm -> do ...
             v -> Left (UnexpectedValue v)
   |
53 |       deps <- tryLookup hm depsKey
   |                         ^^

src/Elm2Nix.hs:56:33: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HashMap Text Value’
      Expected type: HashMap Text Value
        Actual type: Json.Object
    • In the first argument of ‘tryLookup’, namely ‘dhm’
      In a stmt of a 'do' block: direct <- tryLookup dhm "direct"
      In the expression:
        do direct <- tryLookup dhm "direct"
           indirect <- tryLookup dhm "indirect"
           liftM2 (++) (parseDeps direct) (parseDeps indirect)
   |
56 |           direct   <- tryLookup dhm "direct"
   |                                 ^^^

src/Elm2Nix.hs:57:33: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HashMap Text Value’
      Expected type: HashMap Text Value
        Actual type: Json.Object
    • In the first argument of ‘tryLookup’, namely ‘dhm’
      In a stmt of a 'do' block: indirect <- tryLookup dhm "indirect"
      In the expression:
        do direct <- tryLookup dhm "direct"
           indirect <- tryLookup dhm "indirect"
           liftM2 (++) (parseDeps direct) (parseDeps indirect)
   |
57 |           indirect <- tryLookup dhm "indirect"
   |                                 ^^^

src/Elm2Nix.hs:67:64: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HashMap Text Value’
      Expected type: HashMap Text Value
        Actual type: Json.Object
    • In the first argument of ‘HM.toList’, namely ‘hm’
      In the second argument of ‘mapM’, namely ‘(HM.toList hm)’
      In the expression: mapM (uncurry parseDep) (HM.toList hm)
   |
67 |     parseDeps (Object hm) = mapM (uncurry parseDep) (HM.toList hm)
   |                                                                ^^
[4 of 4] Compiling Paths_elm2nix    ( dist/build/autogen/Paths_elm2nix.hs, dist/build/Paths_elm2nix.o, dist/build/Paths_elm2nix.dyn_o )
```

**Comment by sternenseemann** [comment]
Bumping, would be important for GHC 9.0 migration in nixpkgs.

**Comment by gpampara** [comment]
Something like https://github.com/gpampara/elm2nix/commit/1a35f07ad5d63085ffd7e5634355412e1112c4e9 could probably solve this. Just having some GH Actions failures at the moment.
